baseURL: 'https://fdjask1.me/'
languageCode: 'en-us'
title: "fdJasK1's Blog"
theme: "PaperMod"

enableInlineShortcodes: true
enableEmoji: true

hasCJKLanguage: true

paginate: 10

params:
  homeInfoParams:
    Title: 'Hello My Friend <.<'
    Content: 

  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-96x96.png"
    favicon32x32: "favicon-96x96.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "favicon.svg"
    theme_color: "#2e2e33"
    msapplication_TileColor: "#2e2e33"


  socialIcons:
    - name: "github"
      url: "https://github.com/fdJasK1"
    - name: "twitter"
      url: "https://x.com/fdJasK1"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/zr-han-2b3215347/"
    - name: "email"
      url: "mailto:fdjaskl0722@gmail.com"
  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

  math: true

menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1

    - identifier: "archives"
      name: "Archives"
      url: "/archives/"
      weight: 98

    - identifier: "categories"
      name: "Categories"
      url: "/categories/"
      weight: 3

    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 3

    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 99
